/**
 * Real food & drink places in Madinah from the Overture Maps open dataset
 * (https://overturemaps.org), generated by `scripts/import-overture.py`.
 *
 * Open data, compiled from Meta, Microsoft, Foursquare, AllThePlaces and
 * others. It can be incomplete or out of date, and it has no ratings, prices,
 * opening hours or amenities — those fields are null (unknown). Cuisine and
 * category are inferred from Overture's taxonomy and the place name.
 */
import type { AreaId, Cuisine, PlaceCategory, Restaurant } from '../types';

interface RawPlace {
  id: string;
  name: string;
  category: PlaceCategory;
  cuisine: Cuisine;
  area: AreaId;
  lat: number;
  lng: number;
  web?: string;
  tel?: string;
  src: string[];
}

export interface PlacesMeta {
  source: string;
  release: string;
  license: string;
  count: number;
}

export async function loadMadinahPlaces(): Promise<{ meta: PlacesMeta; restaurants: Restaurant[] }> {
  const { default: data } = (await import('./madinahPlaces.json')) as unknown as {
    default: { meta: PlacesMeta; places: RawPlace[] };
  };
  return {
    meta: data.meta,
    restaurants: data.places.map((p) => ({
      id: p.id,
      name: p.name,
      nameEn: p.name,
      category: p.category,
      cuisine: p.cuisine,
      priceLevel: null,
      rating: null,
      area: p.area,
      latitude: p.lat,
      longitude: p.lng,
      openNow: null,
      familyFriendly: null,
      outdoorSeating: null,
      quiet: null,
      groupFriendly: null,
      website: p.web,
      phone: p.tel,
      sources: p.src,
      isSample: false,
    })),
  };
}
